version: '3'

services:
  app:
    build: weatherbot
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
  app_hot_reload:
    build:
      context: weatherbot
      args:
        env: dev
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres:11.4-alpine
    ports:
      - "5432:5432"
    env_file:
      - .env
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  lint:
    build:
      context: weatherbot
      args:
        env: lint
    command: ./scripts/lint
  test:
    build:
      context: weatherbot
      args:
        env: test
    command: ./scripts/test
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    network_mode: host
