version: "3.8"

services:
  weather-smartapp:
    build: .
    container_name: weather-smartapp
    environment:
      - BOT_CREDENTIALS=cts_host@secret_key@bot_id
      - POSTGRES_DSN=postgres://postgres:postgres@weather-smartapp-postgres/weather_smartapp_db
      - DEBUG=true
      - WEATHER_API_URL=https://api.weatherapi.com/v1
      - WEATHER_SECRET_KEYweather_secret_key
    ports:
      - "8000:8000"  # Отредактируйте порт хоста (первый), если он уже занят
    restart: always
    depends_on:
      - postgres
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"

  postgres:
    image: postgres:13.2-alpine
    container_name: weather-smartapp-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=weather_smartapp_db
    restart: always
    volumes:
      - ./.storages/postgresdata:/var/lib/postgresql/data
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"
