version: "3.8"

services:
  weather-smartapp:
    build: .
    container_name: weather-smartapp
    environment:
      - BOT_CREDENTIALS=cts_host@secret_key@bot_id
      - DB_CONNECTION=postgres://postgres_user:postgres_password@postgres/postgres_db
      - SMARTAPP_API_VERSION=1
      - WEATHER_SECRET_KEY=secret
      - DEBUG=false
    ports:
      - "8000:8000"  # Отредактируйте порт хоста (первый), если он уже занят
    restart: always
    depends_on:
      - postgres
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"

  postgres:
    image: postgres:13.2-alpine
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres_user
      - POSTGRES_PASSWORD=postgres_password
      - POSTGRES_DB=postgres_db
    restart: always
    volumes:
      - ./postgresdata:/var/lib/postgresql/data
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"
