"""model user

Revision ID: 467c2429254b
Revises: d6e3a38b1fbd
Create Date: 2022-01-20 12:16:41.174251

Doc: https://alembic.sqlalchemy.org/en/latest/tutorial.html#create-a-migration-script
"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "467c2429254b"
down_revision = "d6e3a38b1fbd"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("user_huid", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("city", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("user_huid"),
    )
    op.drop_table("records")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "records",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("record_data", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("id", name="records_pkey"),
    )
    op.drop_table("user")
    # ### end Alembic commands ###
